# 値の評価と表示

## jsの読み込み

```html
<html>
<head>
    <meta charset="UTF-8">
    <title>Example</title>
    <script src="./index.js"></script>
</head>
<body></body>
</html>
```

この`<script>`タグの中にJavaScriptのコードを記述することもできるが、外部ファイルに記述して読み込むことが一般的。

---

## エラー

### 構文エラー

エラーメッセージはブラウザによって多少の違いはありますが、基本的には同じ形式のメッセージになる。このエラーメッセージをパーツごとに見てみると次のようになる。

```
SyntaxError: missing ) after argument list [詳細] index.js:1:13
^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      ^^^^^^^^  ^^^^
エラーの種類                |                        |   行番号:列番号
                  エラー内容の説明                 ファイル名
```

| メッセージ                                       | 意味                                                            |
|--------------------------------------------------|-----------------------------------------------------------------|
| `SyntaxError: missing ) after argument list`     | エラーの種類はSyntaxErrorで、関数呼び出しの`)`が足りないこと    |
| `index.js:1:13`                                  | ファイル名、行番号、列番号                                      |

## 実行時エラー
実行時エラーはプログラムを実行している最中に発生するエラーです。 実行時（ランタイム）におきるエラーであるため、ランタイムエラーと呼ばれることもあります。 APIに渡す値のデータ型の問題から起きるTypeErrorや存在しない変数を参照しようとして起きるReferenceErrorなどさまざまな種類があります。

実行時エラーが発生した場合は、そのコードは構文としては正しい（構文エラーではない）のですが、別のことが原因でエラーが発生しています。

次のコードではxという存在しない変数を参照したため、ReferenceErrorという実行時エラーが発生しています。
```
index.js
const value = "値";
console.log(x); // => ReferenceError: x is not defined
ReferenceError: x is not defined[詳細] index.js:2:1

メッセージ	意味
```
ReferenceError: x is not defined	エラーの種類はReferenceErrorで、xという未定義の識別子を参照したため発生
index.js:2:1	例外がindex.jsの2行目1列目で発生したこと
xという変数や関数が存在するかは、実行してみないとわかりません。 そのため、実行してxという識別子を参照したときに、初めてxが存在するかが判明し、xが存在しない場合はReferenceErrorとなる。

この例では、value変数を参照しているつもりで、xという存在しない変数を参照していたのが原因。 先ほどのコードは、次のように参照する変数をvalueに変更すれば、エラーが修正できる。
```
const value = "値";
console.log(value); // => "値"
```
このように、実行時エラーは該当する箇所を実行するまで、エラーになるかがわからない場合も多い。 そのため、どこまではちゃんと実行できたか順番に追っていくような、エラーの原因を特定する作業が必要になる場合がある。 このようなエラーの原因を特定し、修正する作業のことをデバッグと呼ぶ。